### ISSUE TITLE
Custom logo in gisquick deployment?

### ISSUE THREAD

**Issue by AndreasAtakan** [gisquick/gisquick-cli#1]
Hi everyone!

I'm wondering if it's possible to create a gisquick deployment with a custom logo replacing the default gisquick logo.
If so, how is this done?

Best regards

**Comment by AndreasAtakan** [comment]
No longer relevant

**Comment by marcel-dancak** [comment]
This form of customization is not directly supported. For most adjustments, it's better to fork related repository, add custom changes, and build custom docker images. In some cases, overriding particular files by mounting them could also work, but it is all up to the users to adjust generated deployment configs.

**Comment by AndreasAtakan** [comment]
Thank you @marcel-dancak, I appreciate the quick response!
If this becomes relevant again, I will be sure to do it through a fork.

Best regards
