### ISSUE TITLE
Sign up webview?

### ISSUE THREAD

**Issue by AndreasAtakan** [gisquick/gisquick-cli#2]
Hi everyone!

I have recently installed gisquick using the gisquick-cli and following the *Https localhost deployment* section.
However, the 'Sign up' button on the landing-page only leads to a 'Page not found'.
How can I include the gisquick/web-accounts container in my gisquick installation?

Best regards

**Comment by AndreasAtakan** [comment]
Fixed in docker compose file

**Comment by marcel-dancak** [comment]
Hi Andreas,

even if you already found a solution by editing docker compose file, actually this option is supported by gisquick-cli. It's not directly documented in README, but there is a note about running `gisquick-cli compose --help` to see all available options. You can use `--accounts` option to include required docker container in generated docker compose file.

**Comment by AndreasAtakan** [comment]
Thank you @marcel-dancak, this is very helpful!
I will be sure to check it out.

Best regards
